name: Deploy to Koyeb


on:
  workflow_run:
    workflows: [ "SonarCloud analysis" ]
    types: [ "completed" ]
    branches: [ "main", "module-2-exercise" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: "progjut"
          service-name: "tutorial2"
          service-instance-type: "free"
          service-ports: "8080:http"
          service-routes: "/:8080"
          service-checks: "8080:tcp"
          git-builder: "docker"